---   
- name: create '{{ postgresql_database }}' service
  k8s_v1_service:
    name: '{{ postgresql_database }}'
    namespace: '{{ namespace }}'
    state: present
    labels:
      app: '{{ postgresql_database }}'
      service: '{{ postgresql_database }}'
    selector:
      app: '{{ postgresql_database }}'
      service: '{{ postgresql_database }}'
    ports:
    - name: "{{ postgresql_database }}-5432"
      port: 5432
      protocol: TCP
      target_port: 5432

- name: create '{{ postgresql_database }}' endpoints
  k8s_v1_endpoints:
    name: '{{ postgresql_database }}'
    namespace: '{{ namespace }}'
    subsets:
    - addresses:
      - ip: '{{postgresql_host}}'
    ports:
      port: 5432
    - name: '{{ postgresql_database }}'

      
- name: Encode '{{ postgresql_database }}' bind credentials
  asb_encode_binding:
    fields:
      DB_TYPE: postgres
      DB_HOST: "{{ postgresql_host }}"
      DB_PORT: "{{ postgresql_port }}"
      DB_USER: "{{ postgresql_user }}"
      DB_PASSWORD: "{{ postgresql_password }}"
      DB_NAME: "{{ postgresql_database }}"
      DB_SCHEMA: "{{ postgresql_schema }}"
