#############################################################################
# Deprovision the service
#############################################################################
- k8s_v1_service:
    name: '{{ postgresql_database }}'
    namespace: '{{ namespace }}'
    state: absent


#############################################################################
# Deprovision the deployment config
# When removing a Deployment Config, OpenShift will automatically clean up
# its associated resources like replication controllers and pods
#############################################################################
- k8s_v1_endpoints:
    name: '{{ postgresql_database }}'
    namespace: '{{ namespace }}'
    state: absent

