oc delete dc beetle
oc delete dc komodo
oc delete dc pg-storage
oc delete service beetle
oc delete service das
oc delete service komodo
oc delete service pg-storage
oc delete deploy das
oc delete route das
